INSERT INTO ROLES ( ID, NAME) VALUES ('1', 'USER')
INSERT INTO USERS  (ID, USERNAME, PASSWORD) VALUES ('1', 'admin', '$2a$10$2lAj3KIS/ddjXXwx80TDnOrEjx1SY73uybK99zj3Q7cZAI3LwguPm')
INSERT INTO USERS_ROLES   (USERS_ID, ROLES_ID) VALUES ('1', '1')